import { Dimensions, StyleSheet } from "react-native";

export const style = StyleSheet.create({

    //Login/Registro
    fundo: {
        flex: 1,
    },
    informar: {
        justifyContent: 'center',
        padding: 30,
        height: Dimensions.get('window').height / 3.2,
        width: '100%',
    },
    container: {
        borderWidth: 2.5,
        borderTopRightRadius: 60,
        borderTopLeftRadius: 60,
        height: Dimensions.get('window').height,
        width: '100%',
        backgroundColor: 'white',
        alignItems: 'center',
    },
    dataimput: {
        borderWidth: .1,
        elevation: 15,
        borderRadius: 10,
        shadowColor: 'green',
        marginTop: 50,
        width: 350,
        height: 160,
        backgroundColor: 'white',
        alignItems: 'center',
        marginBottom: 20,
    },
    dataimputR: {
        borderWidth: .1,
        elevation: 15,
        borderRadius: 10,
        shadowColor: 'green',
        marginTop: 30,
        width: 350,
        height: 320,
        backgroundColor: 'white',
        alignItems: 'center',
        marginBottom: 5,
    },
    caixa: {
        width: '100%',
        height: 46,
        flexDirection: 'row',
    },
    buttom2: {
        width: 140,
        height: 46,
        backgroundColor: 'rgba(246, 255, 251, 0.97),',
        borderRadius: 30,
        marginEnd: 60,
        elevation: 3,
        borderWidth: 0.4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttom3: {
        width: 140,
        height: 46,
        backgroundColor: 'rgba(73, 121, 252, 0.9),',
        borderRadius: 30,
        elevation: 3,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0.4,
    },
    buttom1: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 45,
        width: 140,
        height: 46,
        backgroundColor: 'rgba(102, 225, 170, 0.9),',
        borderRadius: 30,
        elevation: 3,
        marginBottom: 30,
        borderWidth: 0.4,
    },
    buttom1R: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 25,
        width: 140,
        height: 46,
        backgroundColor: 'rgba(102, 225, 170, 0.9),',
        borderRadius: 30,
        elevation: 3,
        marginBottom: 25,
        borderWidth: 0.4,
    },
    imput1: {
        width: 350,
        height: 80,
        borderColor: 'grey',
        borderBottomWidth: 0.2,
        fontSize: 18,
    },
    imput2: {
        width: 350,
        height: 80,
        fontSize: 18,
    },
    //Inicio
    fundoini: {
        backgroundColor: 'white',
        height: Dimensions.get('window').height,
        width: Dimensions.get('window').width,
        flex: 1,
    },
    User: {
        flexDirection: 'row',
        justifyContent: 'space-between', // botão e texto ficam nas pontas
        alignItems: 'center',             // alinha verticalmente
        padding: 10,
        height: Dimensions.get('window').height / 8,
        width: Dimensions.get('window').width,
    },
    UserBt: {
        borderRadius: 20,
        width: 60,
        height: 60,
        marginStart: 5,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(183, 223, 193, 0.82)',
    },
    Search: {
        justifyContent: 'flex-start',
        padding: 10,
        height: Dimensions.get('window').height / 14.5,
        width: Dimensions.get('window').width,
    },
    BarPesq: {
        marginStart:5,
        height: 45,
        width: '98%',
        backgroundColor: 'rgba(204, 204, 204, 0.27)',
        borderRadius: 50,
    },
    Categoria: {
        justifyContent: 'center',
        padding: 10,
        height: Dimensions.get('window').height / 15,
        width: Dimensions.get('window').width,
    },
    CategText: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    Tipos: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        flexDirection: 'row',
        height: Dimensions.get('window').height / 20.5,
        width: Dimensions.get('window').width,
    },
    TiposBt: {
        width: 119,
        height: 43,
        backgroundColor: 'rgba(102, 225, 170, 1)',
        borderRadius: 30,
        elevation: 3,
        borderWidth: 0.4,
        margin: 10,
        textAlign: 'center',
        textAlignVertical: 'center',
        justifyContent: 'center',
        color: 'white',
        fontSize: 17,
        fontFamily: 'Times New Roman',
        fontWeight: 'bold',
    },
    TiposBt2: {
        width: 119,
        height: 43,
        backgroundColor: 'white',
        borderRadius: 30,
        elevation: 3,
        borderWidth: 0.4,
        borderColor: 'rgba(102, 225, 170, 1)',
        margin: 10,
        textAlign: 'center',
        textAlignVertical: 'center',
        justifyContent: 'center',
        color: 'rgba(102, 225, 170, 1)',
        fontSize: 17,
        fontFamily: 'Times New Roman',
        fontWeight: 'bold',
    },
    CarroselCub: {
        top: 20,
        height: Dimensions.get('window').height / 4,
        width: Dimensions.get('window').width,
    },
    CarroselIten: {
        borderRadius: 35,
        padding: 20,
        justifyContent: 'center',
        alignItems: 'center',
        height: 200,
        marginHorizontal: 10,
    },

    //textos
    titulo: {
        fontSize: 40,
        marginTop: 70,
        color: 'white',
        fontFamily: 'Times New Roman',
    },
    subtitulo: {
        marginTop: 22,
        color: 'white',
        fontSize: 18,
        fontFamily: 'Times New Roman',
    },
    textbase1: {
        color: 'grey',
        marginStart: 33,
        marginTop: 10,
        marginBottom: 30,
    },
    textbase2: {
        color: 'grey',
        marginTop: 35,
    },
    textbase3: {
        color: 'grey',
        marginBottom: 25,
    },
    textbase3R: {
        color: 'grey',
        marginBottom: 15,
    },
    textuser: {
        maxWidth: '70%',       // limita o tamanho do texto para 70% da largura
        flexShrink: 1,         // permite o texto encolher se necessário
        fontSize: 22,
        color: '#000',
        fontWeight:'bold',
    },
})
